build: off

clone_folder: c:\gopath\src\github.com\in-toto\in-toto-golang

install:
  - go version
  - go env

test_script:
  - ps: if (gofmt -l in_toto) { Write-Error "Use gofmt" }
  - go test ./...
